/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.wfs.protocol;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class wfsConstants {

  /**
   * 内部版本号
   */
  public static final int wfsprotocolversion = 2;

  /**
   * 外部版本号
   */
  public static final java.lang.String wfsprotocolversionName = "0.0.2";

}
